#!/bin/bash

set -e

SOURCES_DIR="/tmp/artifacts"
SERVER_OVERLAY_ARCHIVE="keycloak-server-overlay.zip"

unzip -o ${SOURCES_DIR}/${SERVER_OVERLAY_ARCHIVE} -d "${JBOSS_HOME}"

echo "Content of ${JBOSS_HOME} directory"
tree "${JBOSS_HOME}"

pushd "${JBOSS_HOME}/bin"
./jboss-cli.sh --file=keycloak-install.cli
popd

# Clean up the left-over content of the history directory
rm -rf "${JBOSS_HOME}/standalone/configuration/standalone_xml_history/current"

chown -R jboss:root "${JBOSS_HOME}"
chmod 0755 "${JBOSS_HOME}"
chmod -R g+rwX "${JBOSS_HOME}"
